/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 benz.glb --transform 
Files: benz.glb [28.79MB] > C:\Users\franc\Desktop\Works\2023Dec\dec\benz-transformed.glb [1.65MB] (94%)
Author: Black Snow (https://sketchfab.com/BlackSnow02)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mersedes-benz-s65-w222-f42d9d13b0404b5b9a2302a4c590a94d
Title: Mersedes-Benz s65 w222
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/benz-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.sw222_engine_2_sw222_main_alt_2_0.geometry} material={materials.PaletteMaterial001} position={[-0.009, 0.765, 1.478]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.sw222_mirror_L_sw222_paint_0.geometry} material={materials.PaletteMaterial002} position={[0.933, 1.039, 0.427]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.sw222_mirror_L_sw222_glass_0.geometry} material={materials.PaletteMaterial003} position={[0.933, 1.039, 0.427]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.sw222_taillightglass_R_2017_glass004_0.geometry} material={materials.PaletteMaterial004} position={[-0.708, 0.855, -2.414]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.sw222_taillightframe_R_2017_sw222_vehiclelights_0.geometry} material={materials.PaletteMaterial005} position={[-0.68, 0.842, -2.426]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/benz-transformed.glb')
